#!/usr/bin/env python3
"""Regenerates the word lists of Wasp.sublime-syntax and Wasp.sublime-completions from warp's sources.

warp (the Rust implementation of wasp) keeps its keywords, word operators, built-in functions, types and units in
tables scattered over src/: constants, match arms and parser calls. SOURCES names them per syntax scope; this script
reads them, keeps the words a wasp program can write, and rewrites the GENERATED block of the syntax's variables and
the completions file. A source that no longer exists is a loud error: warp moved a table and SOURCES must follow.

usage: scripts/update_words.py [path to warp checkout]   (default ~/dev/angles/warp)
"""
import json
import re
import sys
from pathlib import Path

WARP = Path(sys.argv[1] if len(sys.argv) > 1 else "~/dev/angles/warp").expanduser()
PACKAGE = Path(__file__).resolve().parent.parent
SYNTAX = PACKAGE / "Wasp.sublime-syntax"
COMPLETIONS = PACKAGE / "Wasp.sublime-completions"
BEGIN_MARK = "  # BEGIN GENERATED by scripts/update_words.py"
END_MARK = "  # END GENERATED"
WORD = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
# a built-in must appear as a call (`word(`, `.word`, `word x`) in wasp code of the tests, samples or wiki,
# which drops the compiler's internal runtime names (task_spawn, memo_known, …)
USAGE_CORPUS = ["tests", "samples", "wiki"]
# the compiler and its runtime crate (the host words' names live there)
RUST_ROOTS = ["src", "crates/*/src"]
# words some table lists that wasp code never writes as such: compiler-internal or too generic to color
EXCLUDED = {"main", "value", "signal", "event", "fetch", "fd_write", "puti", "putl", "putf",
            "C", "it", "a", "an", "the", "number", "_", "st", "run_block", "foreign_call", "map_entries"}

# Each source: (file in warp, constant name[, "first" | "rest": the first word of each tuple/struct element | the others])
#              ("fn", file, function name): the string and char literals of that function's body
#              ("calls", directory, function name): the literal arguments of calls to that function
#              ("words", word, …): words with no table in warp, kept only while they are a literal in warp's sources
SOURCES = {
	"constant_language": [("fn", "src/wasp_parser/mod.rs", "check_constants"), ("words", "∞")],
	"keyword_control": [
		("src/wasp_parser/mod.rs", "STATEMENT_MODIFIERS", "first"), ("src/wasp_parser/mod.rs", "ELSE_IF_WORDS"),
		("src/wasp_parser/mod.rs", "FALLBACK_WORDS"), ("src/wasp_parser/mod.rs", "UNINDEXABLE_KEYWORDS"),
		("src/wasp_parser/mod.rs", "END_KEYWORD"), ("src/wasp_parser/mod.rs", "AWAIT_KEYWORD"),
		("src/analyzer/mod.rs", "RETURNING_KEYWORDS"), ("src/lowering/switch.rs", "SWITCH_WORDS"),
		("src/lowering/switch.rs", "DEFAULT_KEYS"), ("src/lowering/declarations.rs", "TASK_WORDS"),
		("src/pipeline.rs", "RAISE_WORDS"),
		("words", "for", "loop", "break", "continue", "try", "case", "once", "assert", "with"),
	],
	"keyword_function": [("src/operators.rs", "FUNCTION_KEYWORDS")],
	"keyword_declaration": [
		("src/wasp_parser/mod.rs", "TYPE_DECLARATION_WORDS"),
		("src/wasp_parser/mod.rs", "RECORD_WORD"), ("src/lowering/traits.rs", "TRAIT_KEYWORDS"), ("words", "enum", "data"),
	],
	"keyword_import": [("src/modules.rs", "USE_KEYWORDS"), ("src/wasp_parser/mod.rs", "HASH_DIRECTIVES")],
	"storage_modifier": [
		("src/wasp_parser/mod.rs", "DEFINITION_MODIFIERS"), ("src/wasp_parser/mod.rs", "DECLARATION_MODIFIERS"),
		("src/modules.rs", "DECLARATION_KEYWORDS"), ("src/analyzer/mod.rs", "CONSTANT_KEYWORDS"),
		("src/wasp_parser/mod.rs", "NONLOCAL_WORD"), ("src/lowering/shared_arrays.rs", "SHARED_WORDS"),
		("src/wasp_parser/mod.rs", "FOREIGN_MODIFIERS"),
	],
	"keyword_operator_word": [
		("fn", "src/operators.rs", "as_str"), ("calls", "src/wasp_parser", "matches_keyword"),
		("src/operators.rs", "GLYPH_OPERATORS"), ("src/wasp_parser/mod.rs", "NAND_SPELLINGS"),
		("src/wasp_parser/mod.rs", "SIMILARITY_WORDS"), ("src/wasp_parser/mod.rs", "IS_WORD"),
		("src/wasp_parser/mod.rs", "UPTO"), ("src/wasp_parser/mod.rs", "TIMES_WORD"), ("src/wasp_parser/mod.rs", "TEST_WORDS"),
		("src/wasp_parser/mod.rs", "EVEN_WORD"), ("src/wasp_parser/mod.rs", "ODD_WORD"), ("src/effects.rs", "QUERY_WORDS"),
		("src/lowering/run_time_blocks.rs", "INTERPRET"), ("words", "mod", "rem", "div", "of", "by", "has", "contains"),
	],
	"storage_type": [
		("fn", "src/analyzer/checks.rs", "builtin_type_kind"), ("src/wasp_parser/mod.rs", "LITERAL_NUMBER_TYPES"),
		("src/wasp_parser/mod.rs", "GENERIC_TYPE_HEADS"), ("src/real.rs", "TEXT_TYPES"),
		("src/lowering/traits.rs", "BUILTIN_COMPARABLE"), ("src/analyzer/checks.rs", "MAP_TYPE"),
		("words", "number", "bool", "byte", "char", "symbol", "node", "any", "list", "rational", "complex", "duration",
		 "date", "error", "u8", "u16", "u32", "u64", "i8", "i16"),
	],
	# the user-facing library: every word of these tables is one a program writes
	"support_function": [
		("src/lowering/library_words.rs", "SYNONYMS", "rest"), ("src/lowering/library_words.rs", "LOG_WORD"),
		("src/lowering/library_words.rs", "SUM"), ("src/lowering/library_words.rs", "COUNT_WORD"),
		("src/lowering/lambdas.rs", "ITERATIONS", "first"), ("src/lowering/function_values.rs", "ITERATION_WORDS"),
		("src/lowering/min_max.rs", "EMPTY_LIST_ERRORS", "first"),
		("src/real.rs", "FUNCTIONS"), ("src/host.rs", "HOST_ALIASES", "first"), ("src/lowering/closures.rs", "APPEND_METHODS"),
		("src/lowering/foreign_modules.rs", "COUNTING_WORDS"), ("src/analyzer/mod.rs", "PROPERTYLESS_KEYWORDS"),
		("src/wasp_parser/mod.rs", "HEX_WORD"),
		("words", "now", "range", "len", "length", "size", "min", "max", "abs", "sqrt", "print", "println", "puts",
		 "exit", "read", "round", "pop", "insert", "remove", "keys", "values", "items"),
	],
	# tables of the emitter and the host that mix library words with internal runtime names: a word of these
	# counts as a built-in only where tests, samples or the wiki call it (USAGE_CORPUS)
	"runtime_tables": [
		("src/lowering/library_words.rs", "SYNONYMS", "first"), ("src/wasm_emitter/mod.rs", "ROUNDING_FUNCTIONS"),
		("src/lowering/library_words.rs", "RUNTIME_WORDS", "first"), ("src/lowering/library_words.rs", "EXPANDED_WORDS", "first"),
		("src/wasm_emitter/text_builtins.rs", "TEXT_BUILTINS", "first"), ("src/wasm_emitter/list_emitter.rs", "BUILTIN_CALLS"),
		("src/host.rs", "HOST_WORDS"),
	],
	"time_units": [("fn", "src/time/calendar.rs", "unit_named")],
	"units": [("src/units.rs", "UNITS", "first"), ("src/units.rs", "LONG_NAMES", "first"), ("src/wasp_parser/mod.rs", "UNIT_LOOP_WORDS")],
}
# a word in several scopes keeps the first, in this order (`in` is control flow before it is an operator)
SCOPE_ORDER = list(SOURCES)
CALL_CHECKED = "runtime_tables"
# a type word is also a function where it is called (`map(xs, f)`, `text(42)`), so the built-ins keep type words
SHARED_WORDS = {"support_function": {"storage_type"}, "runtime_tables": {"storage_type"}}
MERGED_INTO = "support_function"

STRING_OR_COMMENT = re.compile(r'"(?:[^"\\]|\\.)*"|//[^\n]*|/\*.*?\*/|\'(?:[^\'\\]|\\.)\'', re.S)
CONST_HEAD = re.compile(r"\b(?:const|static)\s+([A-Z][A-Z0-9_]*)\s*:(?:\[(?:[^\[\]]|\[[^\]]*\])*\]|[^=;])*=")
STRING = re.compile(r'"((?:[^"\\]|\\.)*)"|\'((?:[^\'\\]|\\.))\'')
IDENTIFIER_PATH = re.compile(r"(?:[a-z_][a-z0-9_]*::)*([A-Z][A-Z0-9_]+)(?:\[(\d+)\])?")


def without_comments(code):
	return STRING_OR_COMMENT.sub(lambda m: "" if m.group(0).startswith("/") else m.group(0), code)


def balanced_end(code, start, closing=";"):
	"""Index of `closing` at bracket depth 0 from start (strings and chars already kept intact)"""
	depth = 0
	position = start
	while position < len(code):
		match = STRING_OR_COMMENT.match(code, position)
		if match:
			position = match.end()
			continue
		char = code[position]
		if char in "([{":
			depth += 1
		elif char in ")]}":
			depth -= 1
			if depth < 0:
				return position
		elif char == closing and depth == 0:
			return position
		position += 1
	raise ValueError(f"unbalanced code from {start}")


def top_level_elements(array_body):
	"""The comma separated elements of `[a, (b, c), …]`"""
	inner = array_body.strip()
	if not inner.startswith("["):
		return [inner]
	elements, depth, current, position = [], 0, "", 1
	while position < len(inner) - 1:
		match = STRING_OR_COMMENT.match(inner, position)
		if match:
			current += match.group(0)
			position = match.end()
			continue
		char = inner[position]
		depth += char in "([{"
		depth -= char in ")]}"
		if char == "," and depth == 0:
			elements.append(current)
			current = ""
		else:
			current += char
		position += 1
	return [element for element in elements + [current] if element.strip()]


class RustSources:
	def __init__(self, warp):
		self.files = {path.relative_to(warp).as_posix(): without_comments(path.read_text())
		              for root in RUST_ROOTS for path in warp.glob(f"{root}/**/*.rs")}
		self.constants = {}  # (file, name) → initializer
		for file, code in self.files.items():
			for head in CONST_HEAD.finditer(code):
				self.constants[(file, head.group(1))] = code[head.end():balanced_end(code, head.end())]

	def initializer(self, file, name):
		if (file, name) in self.constants:
			return self.constants[(file, name)]
		elsewhere = [key for key in self.constants if key[1] == name]
		if len(elsewhere) == 1:
			return self.constants[elsewhere[0]]
		raise KeyError(f"warp has no constant {name} in {file} (found in {[key[0] for key in elsewhere]})")

	def strings(self, expression, file):
		"""String literals of an expression, constants it names resolved (`NAME`, `module::NAME`, `NAME[2]`)"""
		words = []
		position = 0
		while position < len(expression):
			string = STRING.match(expression, position)
			identifier = IDENTIFIER_PATH.match(expression, position)
			if string:
				words.append(string.group(1) if string.group(1) is not None else string.group(2))
				position = string.end()
			elif identifier and (position == 0 or not expression[position - 1].isalnum()):
				words += self.resolved(identifier.group(1), identifier.group(2), file)
				position = identifier.end()
			else:
				position += 1
		return words

	def resolved(self, name, index, file):
		try:
			initializer = self.initializer(file, name)
		except KeyError:
			return []  # an enum variant or a type, not a word
		values = self.strings(initializer, file)
		return values[int(index):int(index) + 1] if index is not None else values

	def constant_words(self, file, name, mode=None):
		initializer = self.initializer(file, name)
		if mode in ("first", "rest"):
			elements = [self.strings(element, file) for element in top_level_elements(initializer)]
			return [word for found in elements for word in (found[:1] if mode == "first" else found[1:])]
		return self.strings(initializer, file)

	def function_words(self, file, function):
		code = self.files[file]
		head = re.search(rf"\bfn\s+{function}\b[^{{]*\{{", code)
		if not head:
			raise KeyError(f"warp has no function {function} in {file}")
		return self.strings(code[head.end():balanced_end(code, head.end(), "}")], file)

	def call_arguments(self, directory, function):
		calls = re.compile(rf"\b{function}\(\s*([A-Za-z_:\"][^()]*)\)")
		return [word for file, code in self.files.items() if file.startswith(directory)
		        for argument in calls.findall(code) for word in self.strings(argument, file)]

	def has_literal(self, word):
		return any(f'"{word}"' in code or f"'{word}'" in code for code in self.files.values())


def source_words(rust, source):
	kind = source[0]
	if kind == "fn":
		return rust.function_words(source[1], source[2])
	if kind == "calls":
		return rust.call_arguments(source[1], source[2])
	if kind == "words":
		missing = [word for word in source[1:] if not rust.has_literal(word)]
		if missing:
			print(f"left out, no literal in warp's sources: {missing}", file=sys.stderr)
		return [word for word in source[1:] if word not in missing]
	return rust.constant_words(*source)


def usage_corpus():
	texts = []
	for folder in USAGE_CORPUS:
		for path in (WARP / folder).rglob("*"):
			if path.suffix in {".rs", ".wasp", ".md"} and path.is_file():
				texts.append(path.read_text(errors="ignore"))
	return "\n".join(texts)


def used_as_call(word, corpus):
	return re.search(rf"(?:\.{word}\b|(?<![\w·]){word}\s*\(|(?<![\w·.]){word} +[\w\"'\[(])", corpus) is not None


def is_glyph(token):
	"""An operator or constant written without ASCII: `√`, `⊤`, `ø`, `π`"""
	return bool(token) and not any(char.isascii() for char in token)


def longest_first(found):
	return sorted(found, key=lambda token: (-len(token), token))


def collect_words():
	rust = RustSources(WARP)
	corpus = usage_corpus()
	taken, words = {}, {}  # word → the scope that has it
	for scope in SCOPE_ORDER:
		tokens = {token for source in SOURCES[scope] for token in source_words(rust, source)}
		free = lambda token: token not in taken or taken[token] in SHARED_WORDS.get(scope, ())
		found = {word for word in tokens if WORD.match(word) and word not in EXCLUDED and free(word)}
		if scope == CALL_CHECKED:
			unused = sorted(word for word in found if not used_as_call(word, corpus))
			print(f"runtime names never called in {USAGE_CORPUS}, left out: {unused}", file=sys.stderr)
			found -= set(unused)
			words[MERGED_INTO] = longest_first(set(words[MERGED_INTO]) | found)
		else:
			words[scope] = longest_first(found)
		taken.update({word: scope for word in found if word not in taken})
		glyphs = {token for token in tokens if is_glyph(token) and free(token)}
		glyph_key = f"{MERGED_INTO if scope == CALL_CHECKED else scope}_glyphs"
		words[glyph_key] = longest_first(set(words.get(glyph_key, [])) | glyphs)
		taken.update({glyph: scope for glyph in glyphs if glyph not in taken})
	return words


def generated_variables(words, syntax):
	"""A variable per word list the syntax names or that has words; an empty one never matches"""
	lines = [BEGIN_MARK, "  # from warp's sources, see SOURCES in scripts/update_words.py; rerun instead of editing"]
	lines += [f"  {scope}: (?:{'|'.join(map(re.escape, found)) or '(?!)'})" for scope, found in words.items()
	          if found or "{{" + scope + "}}" in syntax]
	return lines + [END_MARK]


def rewrite_syntax(words):
	text = SYNTAX.read_text()
	begin, end = text.index(BEGIN_MARK), text.index(END_MARK) + len(END_MARK)
	SYNTAX.write_text(text[:begin] + "\n".join(generated_variables(words, text)) + text[end:])


def write_completions(words):
	completions = [{"trigger": f"{word}\tbuilt-in", "contents": f"{word}($1)"} for word in sorted(words["support_function"])]
	completions += [{"trigger": f"{word}\t{scope.replace('_', ' ')}", "contents": word}
	                for scope in ["keyword_control", "keyword_function", "keyword_declaration", "keyword_import", "storage_modifier",
	                              "keyword_operator_word", "storage_type", "constant_language"]
	                for word in sorted(words[scope])]
	rows = ",\n".join("\t\t" + json.dumps(completion, ensure_ascii=False) for completion in completions)
	COMPLETIONS.write_text(f'{{\n\t"scope": "source.wasp",\n\t"completions": [\n{rows}\n\t]\n}}\n')


if __name__ == "__main__":
	found_words = collect_words()
	rewrite_syntax(found_words)
	write_completions(found_words)
	for scope, found in found_words.items():
		print(f"{scope} ({len(found)}): {' '.join(sorted(found))}")
